---
- hosts: sprint2

  tasks:
  - name: Update APT package manager repositories cache
    become: true
    apt:
      update_cache: yes

  - name: Install OpenJDK Java
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - openjdk-8-jdk
     - python3
     - git
     - nginx
     - postgresql