---
sonar_username: 'sonar'
sonar_dependencies:
  - 'java-1.8.0-openjdk'
  - 'sonar-5.3'
sonar_repo: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.2.0.32929.zip"
postgres_repo: 'http://yum.postgresql.org/9.3/redhat/rhel-7-x86_64/pgdg-centos93-9.3-2.noarch.rpm'
