---


        #SonarRunner
        - name: Download and expand sonar-runner.
          unarchive:
            src: "https://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip"
            dest: "/home/ubuntu"
            copy: no
            creates: /usr/local/sonar-runner/bin/sonar-runner

        - name: Move sonar-runner into place.
          shell: > 
            mv /home/ubuntu/sonar-runner-2.4 /home/ubuntu/sonar-runner
            creates=/home/ubuntu/sonar-runner/bin/sonar-runner

         #SonarQube
        - name: Download Sonar.
          get_url:
            url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.2.0.32929.zip"
            dest: "/root/sonarqube-8.2.0.32929.zip"
            validate_certs: yes

        - name: Unzip Sonar.
          unarchive:
            src: "/root/sonarqube-8.2.0.32929.zip"
            dest: /home/ubuntu
            copy: no
            creates: /home/ubuntu/sonar/COPYING

        - name: Move Sonar into place.
          shell: > 
            mv /home/ubuntu/sonarqube-8.2.0.32929 /home/ubuntu/sonar
            creates=/home/ubuntu/sonar/COPYING

        - name: Symlink sonar bin.
          file:
            src: /home/ubuntu/sonar/bin/linux-x86-64/sonar.sh
            dest: /usr/bin/sonar
            state: link
          register: sonar_symlink

        - name: Add sonar as init script for service management.
          file:
            src: /home/ubuntu/sonar/bin/linux-x86-64/sonar.sh
            dest: /etc/init.d/sonar
            state: link
          notify:
              - 'restart sonar'
   
